version: '3'
services:
  mysql:
    image: mysql:5.7.28
    container_name: attorney_mysql
    volumes:
      - ./attorney-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: attorneys
      MYSQL_USER: attorney_user
      MYSQL_PASSWORD: strong_password
